Repository CntoDev/cba-settings-lock, pull requests merged in 2021-05, with the labels that each got.

#41 V2.2.4 Update
  cba_settings_userconfig/cba_settings.sqf
Labels: Enhancement, Update

#43 add defaults.sqf representing mod default CBA settings
  cba_settings_userconfig/defaults.sqf
Labels: Documentation

#45 v2.2.5 Update
  cba_settings_userconfig/cba_settings.sqf
Labels: Bug
